### ISSUE TITLE
Lesson 1. DOM

### ISSUE THREAD

**Issue by AsterAI** [radykhovskyi/radykhovskyi.github.io#1]
Ноды не вложены.  Пожалуйста вложите дочерние папки в нутрь родителей (div положить в внутрь другого div)

**Comment by radykhovskyi** [comment]
@AsterAI исправил
Github - https://github.com/radykhovskyi/radykhovskyi.github.io/blob/master/dom/task1/index.html
Github Pages - https://radykhovskyi.github.io/dom/task1/index.html
